[package]
name = "stratum-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
rsq = { path = "../" }
tokio = { version = "1.0", features = ["full"] }
num_cpus = "1.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
sha2 = "0.10"
